version: '3'

services:
  frontend:
    image: 'expense-tracker-frontend'
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    image: 'expense-tracker-backend'
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
